### ISSUE TITLE
Error fetching updates: null spamming logs

### ISSUE THREAD

**Issue by lionep** [ilcato/homebridge-fibaro-hc3#11]
Hello,

First, thanks for this great project, it's mostly the only homebridge plugin I'm using.

In logs, I've this message showing 2 times every 5 seconds :
```
[11/21/2020, 5:14:25 PM] [FibaroHC3] Error fetching updates:  null
[11/21/2020, 5:14:29 PM] [FibaroHC3] Error fetching updates:  null
[11/21/2020, 5:14:30 PM] [FibaroHC3] Error fetching updates:  null
[11/21/2020, 5:14:34 PM] [FibaroHC3] Error fetching updates:  null
```

Here is the config.json : 
```json
{
  "name": "FibaroHC3",
  "host": "10.0.0.50",
  "username": "api",
  "password": "*************",
  "pollerperiod": 1,
  "securitysystem": "enabled",
  "platform": "FibaroHC3"
}
```

I created a dedicated user on Fibaro HC3 for this plugins, of type "user", with access to every device, every scene, every alarm zones and every profiles.

I can do some tests, to help for this.

**Comment by ilcato** [comment]
@lionep is everything else working? I Homekit receiving updates from home center?

**Comment by lionep** [comment]
Hello, yes, almost everything : security system hand with no response, when changing the value from Homekit.

It looks like I don't have the log anymore after upgrading to v1.0.7 and upgrading homebridge, but I have this log, that may be related : 

```
[12/7/2020, 10:31:11 PM] [FibaroHC3] There was a problem getting value from Global Variabls  - Err: null
(node:14866) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'delay' of undefined
    at FibaroHC3.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-hc3/src/index.ts:351:18)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/homebridge-fibaro-hc3/dist/index.js:39:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Let me know how I can help.

**Comment by ilcato** [comment]
Can you disable in config.json the security system flag and the global variable if you use it?

**Comment by lionep** [comment]
It looks like putting `"securitysystem": "disabled",` silence the log.

**Comment by ilcato** [comment]
Was "securitysystem" ever working? Did you configured all the parts?

**Comment by ilcato** [comment]
@lionep, any news?
