### ISSUE TITLE
Homebridge v1.3.1 issue (Security System Target State)

### ISSUE THREAD

**Issue by dazcro** [ilcato/homebridge-fibaro-hc3#28]
Homebridge v1.3.1 has an issue trying to read the Security System Target State.

Please see debug logs below.
 
[2/27/2021, 11:57:22 PM] [homebridge-fibaro-hc3] This plugin generated a warning from the characteristic 'Security System Target State': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.
[2/27/2021, 11:57:22 PM] [homebridge-fibaro-hc3] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1996:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GetFunctions.returnValue (/homebridge/node_modules/homebridge-fibaro-hc3/src/getFunctions.ts:83:4)
    at GetFunctions.getSecuritySystemState (/homebridge/node_modules/homebridge-fibaro-hc3/src/getFunctions.ts:297:8)
    at FibaroHC3.<anonymous> (/homebridge/node_modules/homebridge-fibaro-hc3/src/index.ts:334:24)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-fibaro-hc3/dist/index.js:39:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by ilcato** [comment]
@dazcro, can you update to last version and check if this is still an issue?

**Comment by dazcro** [comment]
> @dazcro, can you update to last version and check if this is still an issue?

Hi, It still seems to be an issue: see below.

HomeBridge: 1.3.4
homebridge-fibaro-hc3: v1.1.7

<img width="1233" alt="Screen Shot 2021-03-26 at 11 28 59 pm" src="https://user-images.githubusercontent.com/25233409/112631566-29ee1800-8e8b-11eb-90b5-2cccd2c5ef03.png">

**Comment by ilcato** [comment]
@dazcro, can you test 1.1.8 ?

**Comment by dazcro** [comment]
> @dazcro, can you test 1.1.8 ?

Thanks thats all fixed it, I just wanted to ask, is there anything special i need to do to toggle the alarm settings from my home app on iphone, it looks like homebridge can toggle the fibaro alarm system, but when i do it from the home app, its unresponsive.
