### ISSUE TITLE
Error with 'getCharacteristic' 

### ISSUE THREAD

**Issue by antoniopll** [ilcato/homebridge-fibaro-hc3#3]
Hello,
I have this error when I start homebridge:
[4/27/2020, 10:00:41 AM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at Accessory._this._sideloadServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1046:17)
    at Function.Accessory.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1681:15)
    at Function.deserialize (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:151:33)
    at /usr/lib/node_modules/homebridge/src/server.ts:261:34
    at Array.map (<anonymous>)
    at Server.loadCachedPlatformAccessoriesFromDisk (/usr/lib/node_modules/homebridge/src/server.ts:260:58)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:147:10)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)

**Comment by ilcato** [comment]
Try with the new version.
Delete the accessories folder in case of further problems.

**Comment by antoniopll** [comment]
Yeah! Deleting the accessories folder and restarting homebridge, now is working.
Thanks!
