### ISSUE TITLE
Global variable switch error

### ISSUE THREAD

**Issue by KJTamas** [ilcato/homebridge-fibaro-hc3#40]
Hi @ilcato ,

I updated my fibaro hc3 plugins to 1.1.10, and i get an error: 

[3/29/2021, 11:16:01 AM] [FibaroHC3] Error fetching updates:  TypeError: Cannot read property 'value' of null
    at GetFunctions.getBool (/homebridge/node_modules/homebridge-fibaro-hc3/src/getFunctions.ts:83:22)
    at Poller.<anonymous> (/homebridge/node_modules/homebridge-fibaro-hc3/src/pollerupdate.ts:69:33)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-fibaro-hc3/dist/pollerupdate.js:19:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

This feature worked in previous version.
thx

**Comment by ilcato** [comment]
Fixed, it will be available in version 1.1.11

**Comment by ilcato** [comment]
1.1.11 published. @KJTamas can you check the issue?

**Comment by KJTamas** [comment]
Hi,

Sorry, but not working…

3/30/2021, 4:13:31 PM] [FibaroHC3] Setting value to device:  Test  parameter: On
[3/30/2021, 4:13:32 PM] [FibaroHC3] There was a problem sending command  pressButton to G

In Home app i press Test button, (default = ON),  button status turn to Off, in log appears the action, and button status change back to on. In HC3 i can't see any event.

Br,

Tamas

**Comment by ilcato** [comment]
@KJTamas can you test 1.1.12?

**Comment by KJTamas** [comment]
Hi,

It’s all right! It’s working.

thx
